name: Nightly LLM Red-Team
on:
  schedule: [ { cron: '0 3 * * *' } ]   # 03:00 UTC daily
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with: { python-version: '3.11' }
    - run: pip install -r requirements.txt
    - env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute notebook.ipynb \
                         --output executed.ipynb
    - uses: actions/upload-artifact@v4
      with: { name: nightly-results, path: results.jsonl }